FROM hseeberger/scala-sbt:graalvm-ce-21.2.0-java11_1.5.5_3.0.1
# RUN ["apk", "update"]
# RUN ["apk", "add", "nginx"]
# RUN ["mkdir", "-p", "/run/nginx"]
# RUN ["mkdir", "-p", "/usr/share/nginx/html"]
# EXPOSE 80
# COPY nginx.conf /etc/nginx/http.d/default.conf
# RUN /usr/sbin/nginx -g "daemon off;"
CMD sbt "~fastLinkJS"
