version: "3.3"
volumes:
  frontend-static:
services:
  frontend:
    working_dir: /app
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/resources:/app/frontend/resources
      - frontend-static:/app/frontend/target/scala-2.13/with-html
      - ./common/src:/app/common/src
      - ./project:/app/project
      - ./build.sbt:/app/build.sbt
      - /root/.cache
    image: hseeberger/scala-sbt:graalvm-ce-21.3.0-java17_1.6.1_3.1.0
    entrypoint: sbt "~fastOptCompileCopy"
  frontend-server:
    working_dir: /app
    volumes:
      - frontend-static:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    image: nginx:alpine
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - frontend
    ports:
      - "9001:80"
  postgres:
    working_dir: /db
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=dbpassword
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/main/resources/sql:/docker-entrypoint-initdb.d/
  backend:
    working_dir: /app
    image: hseeberger/scala-sbt:graalvm-ce-21.3.0-java17_1.6.1_3.1.0
    entrypoint: sbt "~backend/reStart"
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/target/scala-2.13/src_managed:/app/backend/target/scala-2.13/src_managed
      - ./common/src:/app/common/src
      - ./project:/app/project
      - ./build.sbt:/app/build.sbt
      - /root/.cache
    ports:
      - "9000:9000"
