version: "3.8"
services:
  frontend:
    working_dir: /app
    volumes:
      - ./frontend:/app/frontend
      - ./common:/app/common
      - ./project:/app/project
      - ./build.sbt:/app/build.sbt
      - /root/.cache
    image: hseeberger/scala-sbt:graalvm-ce-21.2.0-java11_1.5.5_3.0.1
    entrypoint: sbt "~fastOptCompileCopy"
  frontend-server:
    working_dir: /app
    volumes:
      - ./frontend/resources:/usr/share/nginx/html
    image: nginx:1.21.1-alpine
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - frontend
    ports:
      - "80:80"
  backend:
    working_dir: /app
    image: hseeberger/scala-sbt:graalvm-ce-21.2.0-java11_1.5.5_3.0.1
    entrypoint: sbt "~backend/reStart"
    depends_on:
      - frontend-server
    volumes:
      - ./backend:/app/backend
      - ./common:/app/common
      - ./project:/app/project
      - ./build.sbt:/app/build.sbt
      - /root/.cache
    ports:
      - "9000:9000"
