addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.9.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.10.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-pack"                 % "0.14")
addSbtPlugin("com.codecommit"     % "sbt-github-packages"      % "0.5.3")
