name: Scala CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add git config
      run: |
          echo $GH_CONFIG_FILE >> ~/.gitconfig
      shell: bash
      env: 
        GH_CONFIG_FILE : ${{secrets.GH_CONFIG_FILE}}
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Compile
      run: sbt backend/compile
